/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as ToolToolRouteImport } from './routes/tool.$tool'
import { Route as SitemapLocaleRouteImport } from './routes/sitemap/$locale'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LocaleToolsRouteImport } from './routes/$locale.tools'
import { Route as LocaleTermsRouteImport } from './routes/$locale.terms'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleLearnRouteImport } from './routes/$locale.learn'
import { Route as LocaleDmcaRouteImport } from './routes/$locale.dmca'
import { Route as LocaleDisclaimerRouteImport } from './routes/$locale.disclaimer'
import { Route as LocaleCookiePolicyRouteImport } from './routes/$locale.cookie-policy'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale.blog.index'
import { Route as LocaleToolToolRouteImport } from './routes/$locale.tool.$tool'
import { Route as LocaleCategoryCategoryRouteImport } from './routes/$locale.category.$category'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale.blog.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const ToolToolRoute = ToolToolRouteImport.update({
  id: '/tool/$tool',
  path: '/tool/$tool',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapLocaleRoute = SitemapLocaleRouteImport.update({
  id: '/sitemap/$locale',
  path: '/sitemap/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleToolsRoute = LocaleToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLearnRoute = LocaleLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDmcaRoute = LocaleDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDisclaimerRoute = LocaleDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCookiePolicyRoute = LocaleCookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleToolToolRoute = LocaleToolToolRouteImport.update({
  id: '/tool/$tool',
  path: '/tool/$tool',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCategoryCategoryRoute = LocaleCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cookie-policy': typeof LocaleCookiePolicyRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/dmca': typeof LocaleDmcaRoute
  '/$locale/learn': typeof LocaleLearnRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/tools': typeof LocaleToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/sitemap/$locale': typeof SitemapLocaleRoute
  '/tool/$tool': typeof ToolToolRoute
  '/$locale/': typeof LocaleIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/category/$category': typeof LocaleCategoryCategoryRoute
  '/$locale/tool/$tool': typeof LocaleToolToolRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cookie-policy': typeof LocaleCookiePolicyRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/dmca': typeof LocaleDmcaRoute
  '/$locale/learn': typeof LocaleLearnRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/tools': typeof LocaleToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/sitemap/$locale': typeof SitemapLocaleRoute
  '/tool/$tool': typeof ToolToolRoute
  '/$locale': typeof LocaleIndexRoute
  '/blog': typeof BlogIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/category/$category': typeof LocaleCategoryCategoryRoute
  '/$locale/tool/$tool': typeof LocaleToolToolRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cookie-policy': typeof LocaleCookiePolicyRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/dmca': typeof LocaleDmcaRoute
  '/$locale/learn': typeof LocaleLearnRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/tools': typeof LocaleToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/sitemap/$locale': typeof SitemapLocaleRoute
  '/tool/$tool': typeof ToolToolRoute
  '/$locale/': typeof LocaleIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/category/$category': typeof LocaleCategoryCategoryRoute
  '/$locale/tool/$tool': typeof LocaleToolToolRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/dmca'
    | '/learn'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/cookie-policy'
    | '/$locale/disclaimer'
    | '/$locale/dmca'
    | '/$locale/learn'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/tools'
    | '/blog/$slug'
    | '/category/$category'
    | '/sitemap/$locale'
    | '/tool/$tool'
    | '/$locale/'
    | '/blog/'
    | '/$locale/blog/$slug'
    | '/$locale/category/$category'
    | '/$locale/tool/$tool'
    | '/$locale/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/dmca'
    | '/learn'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/cookie-policy'
    | '/$locale/disclaimer'
    | '/$locale/dmca'
    | '/$locale/learn'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/tools'
    | '/blog/$slug'
    | '/category/$category'
    | '/sitemap/$locale'
    | '/tool/$tool'
    | '/$locale'
    | '/blog'
    | '/$locale/blog/$slug'
    | '/$locale/category/$category'
    | '/$locale/tool/$tool'
    | '/$locale/blog'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/dmca'
    | '/learn'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/cookie-policy'
    | '/$locale/disclaimer'
    | '/$locale/dmca'
    | '/$locale/learn'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/tools'
    | '/blog/$slug'
    | '/category/$category'
    | '/sitemap/$locale'
    | '/tool/$tool'
    | '/$locale/'
    | '/blog/'
    | '/$locale/blog/$slug'
    | '/$locale/category/$category'
    | '/$locale/tool/$tool'
    | '/$locale/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DmcaRoute: typeof DmcaRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  SitemapLocaleRoute: typeof SitemapLocaleRoute
  ToolToolRoute: typeof ToolToolRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/tool/$tool': {
      id: '/tool/$tool'
      path: '/tool/$tool'
      fullPath: '/tool/$tool'
      preLoaderRoute: typeof ToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$locale': {
      id: '/sitemap/$locale'
      path: '/sitemap/$locale'
      fullPath: '/sitemap/$locale'
      preLoaderRoute: typeof SitemapLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/tools': {
      id: '/$locale/tools'
      path: '/tools'
      fullPath: '/$locale/tools'
      preLoaderRoute: typeof LocaleToolsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/learn': {
      id: '/$locale/learn'
      path: '/learn'
      fullPath: '/$locale/learn'
      preLoaderRoute: typeof LocaleLearnRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dmca': {
      id: '/$locale/dmca'
      path: '/dmca'
      fullPath: '/$locale/dmca'
      preLoaderRoute: typeof LocaleDmcaRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/disclaimer': {
      id: '/$locale/disclaimer'
      path: '/disclaimer'
      fullPath: '/$locale/disclaimer'
      preLoaderRoute: typeof LocaleDisclaimerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cookie-policy': {
      id: '/$locale/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/$locale/cookie-policy'
      preLoaderRoute: typeof LocaleCookiePolicyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tool/$tool': {
      id: '/$locale/tool/$tool'
      path: '/tool/$tool'
      fullPath: '/$locale/tool/$tool'
      preLoaderRoute: typeof LocaleToolToolRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/category/$category': {
      id: '/$locale/category/$category'
      path: '/category/$category'
      fullPath: '/$locale/category/$category'
      preLoaderRoute: typeof LocaleCategoryCategoryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleCookiePolicyRoute: typeof LocaleCookiePolicyRoute
  LocaleDisclaimerRoute: typeof LocaleDisclaimerRoute
  LocaleDmcaRoute: typeof LocaleDmcaRoute
  LocaleLearnRoute: typeof LocaleLearnRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleToolsRoute: typeof LocaleToolsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleCategoryCategoryRoute: typeof LocaleCategoryCategoryRoute
  LocaleToolToolRoute: typeof LocaleToolToolRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleCookiePolicyRoute: LocaleCookiePolicyRoute,
  LocaleDisclaimerRoute: LocaleDisclaimerRoute,
  LocaleDmcaRoute: LocaleDmcaRoute,
  LocaleLearnRoute: LocaleLearnRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleToolsRoute: LocaleToolsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleCategoryCategoryRoute: LocaleCategoryCategoryRoute,
  LocaleToolToolRoute: LocaleToolToolRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  DmcaRoute: DmcaRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  SitemapLocaleRoute: SitemapLocaleRoute,
  ToolToolRoute: ToolToolRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
